// BACKEND_SCHEMA - Template generated by Cerber
// ⚠️ THIS IS NOT SOURCE OF TRUTH - CERBER.md is the contract
export const BACKEND_SCHEMA = {
  forbiddenPatterns: [
    {
      pattern: "password\\s*=\\s*['\"][^'\"]+['\"]",
      flags: "i",
      name: "Hardcoded passwords",
      severity: "error"
    },
    {
      pattern: "api[_-]?key\\s*=\\s*['\"][^'\"]+['\"]",
      flags: "i",
      name: "Hardcoded API keys",
      severity: "error"
    }
  ]
};
