// Generated by Cerber init - CUSTOMIZE THIS FILE

import { checks } from './health-checks.js';

export async function healthHandler(req: any, res: any) {
  const startTime = Date.now();

  try {
    const results = await Promise.all(
      Object.entries(checks).map(async ([name, check]) => ({
        name,
        issues: await check()
      }))
    );

    const allIssues = results.flatMap(r => r.issues);
    const critical = allIssues.filter(i => i.severity === 'critical').length;
    const errors = allIssues.filter(i => i.severity === 'error').length;
    const warnings = allIssues.filter(i => i.severity === 'warning').length;

    const status = critical > 0 ? 'unhealthy' :
                   errors > 0 ? 'degraded' : 'healthy';

    const statusCode = status === 'healthy' ? 200 : 503;

    res.status(statusCode).json({
      status,
      timestamp: new Date().toISOString(),
      durationMs: Date.now() - startTime,
      summary: {
        totalChecks: results.length,
        failedChecks: results.filter(r => r.issues.length > 0).length,
        criticalIssues: critical,
        errorIssues: errors,
        warningIssues: warnings
      },
      components: allIssues
    });
  } catch (err: any) {
    res.status(503).json({
      status: 'error',
      message: 'Health check failed',
      error: err.message
    });
  }
}

// Usage in your server:
// import { healthHandler } from './cerber/health-route.js';
// app.get('/api/health', healthHandler);
